# Generated by Django 4.0.1 on 2022-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=40)),
                ('club_name', models.CharField(max_length=45, null=True)),
                ('image_club', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
