# Generated by Django 4.0.1 on 2022-05-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser_group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.teacher')),
            ],
        ),
    ]
