# Generated by Django 4.0.1 on 2022-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0004_adviser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_name',
            fields=[
                ('course_code', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
