# Generated by Django 4.0.1 on 2022-05-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0005_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_has_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.course_name')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.teacher')),
            ],
        ),
    ]
