# Generated by Django 4.0.1 on 2022-05-12 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back_project', '0006_teachers_has_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('image_stud', models.ImageField(upload_to='img/')),
                ('phone', models.CharField(max_length=40, null=True)),
                ('current_course', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('club_id', models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='back_project.club')),
                ('group_id', models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='back_project.adviser_group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
