# Generated by Django 4.0.1 on 2022-05-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0008_student_has_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('proff', models.CharField(max_length=45, null=True)),
                ('age', models.IntegerField(null=True)),
                ('student_id', models.IntegerField(null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('status', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], max_length=25, null=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.student_has_parent')),
            ],
        ),
    ]
