# Generated by Django 4.0.1 on 2022-05-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0009_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother')], null=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.parent')),
            ],
        ),
    ]
