# Generated by Django 4.0.1 on 2022-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0010_parent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
