# Generated by Django 4.0.1 on 2022-05-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0011_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proff_id', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IS'), (2, 'CS'), (3, 'Mcm'), (4, 'MathSc'), (5, 'MathPed'), (6, 'TFL'), (7, 'Bioch')], null=True)),
                ('proff_name', models.CharField(max_length=45, null=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.faculty')),
            ],
        ),
    ]
