# Generated by Django 4.0.1 on 2022-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0012_proff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_course', models.IntegerField(null=True)),
                ('season_semester', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
