# Generated by Django 4.0.1 on 2022-05-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0013_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_format',
            fields=[
                ('exam_format_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_format_name', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=45, null=True)),
                ('exam_format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.exam_format')),
            ],
        ),
    ]
