# Generated by Django 4.0.1 on 2022-05-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0015_course_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_att', models.TimeField(null=True)),
                ('date_att', models.DateField(null=True)),
                ('mark_att', models.BooleanField(null=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_project.student')),
            ],
        ),
    ]
