# Generated by Django 4.0.1 on 2022-05-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0016_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_format_id',
        ),
        migrations.DeleteModel(
            name='Exam_format',
        ),
    ]
