# Generated by Django 4.0.1 on 2022-05-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0017_remove_exam_exam_format_id_delete_exam_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cr',
            field=models.IntegerField(null=True),
        ),
    ]
