# Generated by Django 4.0.1 on 2022-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0018_grade_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='cr',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
