# Generated by Django 4.0.1 on 2022-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0020_remove_course_credit_grade_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
