# Generated by Django 4.0.1 on 2022-05-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0022_remove_parent_id_alter_parent_parent_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent_status',
        ),
    ]
