# Generated by Django 4.0.1 on 2022-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0024_parent_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent_status',
        ),
    ]
