# Generated by Django 4.0.2 on 2022-05-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0026_parent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='link_discord',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='link_instagram',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='link_telegram',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
