# Generated by Django 4.0.2 on 2022-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0027_club_link_discord_club_link_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='proff',
            field=models.CharField(choices=[('IS', 'Information Systems'), ('CS', 'Computer Science'), ('MCM', 'Math computer model'), ('MathSc', 'Math Science'), ('MathPed', 'Math Ped'), ('TFL', 'TFL'), ('Bioch', 'Bioch')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proff',
            name='proff_id',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('IS', 'Information Systems'), ('CS', 'Computer Science'), ('MCM', 'Math computer model'), ('MathSc', 'Math Science'), ('MathPed', 'Math Ped'), ('TFL', 'TFL'), ('Bioch', 'Bioch')], null=True),
        ),
    ]
