# Generated by Django 4.0.2 on 2022-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0029_alter_proff_proff_id_alter_student_proff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
