# Generated by Django 4.0.2 on 2022-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_project', '0032_alter_teacher_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1970-01-01', null=True),
        ),
    ]
